{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "flusso.fullname" .) }}
  labels:
    {{- include "flusso.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
