[package]
name = "flusso-stream-channel"
version = "0.16.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "In-process channel queue implementation for flusso."
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
categories = ["database"]
readme.workspace = true

[lib]
name = "stream_channel"

[lints]
workspace = true

[dependencies]
stream.workspace = true
kernel = { workspace = true, features = ["derive"] }
serde.workspace = true
schemars.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
toml.workspace = true
