//! Idle-slot e2e: with every watched table quiet, WAL generated by unrelated
//! writes must not pin the slot — keepalive-driven progress has to advance
//! `confirmed_flush_lsn` past it (issue #111 regression net).
//!
//! Requires Docker. Ignored by default; run with:
//!
//! ```text
//! cargo test -p sources-postgres --test wal_idle -- --ignored
//! ```

#![allow(clippy::unwrap_used, unused_crate_dependencies)]

use std::collections::BTreeSet;
use std::time::{Duration, Instant};

use futures::StreamExt;
use schema_core::{DatabaseSchema, TableName};
use sources_core::QualifiedTable;
use sources_core::cdc::ChangeCapture;
use sources_postgres::{ReplicationConfig, WalChangeCapture};
use sqlx::Row;
use sqlx::postgres::PgPoolOptions;
use testcontainers_modules::postgres::Postgres;
use testcontainers_modules::testcontainers::ImageExt;
use testcontainers_modules::testcontainers::runners::AsyncRunner;

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
#[ignore = "requires docker"]
async fn slot_advances_while_watched_tables_are_idle() {
    // A short wal_sender_timeout makes the server send keepalives every ~1s of
    // inactivity, so the idle advance is observable within the test deadline.
    let container = Postgres::default()
        .with_tag("16-alpine")
        .with_cmd([
            "postgres",
            "-c",
            "wal_level=logical",
            "-c",
            "max_wal_senders=10",
            "-c",
            "max_replication_slots=10",
            "-c",
            "wal_sender_timeout=2s",
        ])
        .start()
        .await
        .unwrap();
    let port = container.get_host_port_ipv4(5432).await.unwrap();
    let url = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");

    let pool = PgPoolOptions::new().connect(&url).await.unwrap();
    for statement in [
        "CREATE TABLE users (id int PRIMARY KEY, email text)",
        "CREATE TABLE noise (id serial PRIMARY KEY, payload text)",
    ] {
        sqlx::query(statement).execute(&pool).await.unwrap();
    }

    let replication = ReplicationConfig::new(
        "127.0.0.1",
        "postgres",
        "postgres",
        "postgres",
        "flusso",
        "flusso",
    )
    .with_port(port)
    .with_status_interval(Duration::from_secs(1));
    let watched = BTreeSet::from([QualifiedTable::new(
        DatabaseSchema::try_new("public").unwrap(),
        TableName::try_new("users").unwrap(),
    )]);
    let capture =
        WalChangeCapture::new(replication, url.clone()).with_publication_management(watched, true);

    // `live` creates the slot and the publication (covering only `users`). The
    // stream must be driven for keepalives to reach the watermark, so poll it
    // from a task; no change should ever arrive.
    let mut stream = capture.live().await.unwrap();
    let driver = tokio::spawn(async move {
        while let Some(change) = stream.next().await {
            panic!("unexpected change from an idle watched table: {change:?}");
        }
    });

    // WAL from the unwatched table only, then the position it must clear.
    for _ in 0..50 {
        sqlx::query("INSERT INTO noise (payload) VALUES (repeat('x', 1000))")
            .execute(&pool)
            .await
            .unwrap();
    }
    let target: String = sqlx::query("SELECT pg_current_wal_lsn()::text AS lsn")
        .fetch_one(&pool)
        .await
        .unwrap()
        .try_get("lsn")
        .unwrap();

    let deadline = Instant::now() + Duration::from_secs(60);
    loop {
        let diff: i64 = sqlx::query(
            "SELECT pg_wal_lsn_diff(confirmed_flush_lsn, $1::pg_lsn)::bigint AS diff \
             FROM pg_replication_slots WHERE slot_name = 'flusso'",
        )
        .bind(&target)
        .fetch_one(&pool)
        .await
        .unwrap()
        .try_get("diff")
        .unwrap();
        if diff >= 0 {
            break;
        }
        assert!(
            Instant::now() < deadline,
            "confirmed_flush_lsn never reached {target} (still {} bytes behind)",
            -diff,
        );
        tokio::time::sleep(Duration::from_millis(250)).await;
    }

    driver.abort();
}
