//! Compiling a configuration into a single, portable text artifact.
//!
//! [`compile`] runs the whole load pipeline — read `flusso.toml`, parse every
//! referenced schema, validate and convert into a [`Config`] — and wraps the
//! result in a [`Compiled`] envelope. [`write`](fn@write) serializes that
//! envelope to deterministic TOML; [`load_compiled`] reads it back.
//!
//! The point is deployment: a compiled artifact is one file that carries the
//! full, validated configuration with no scattered YAML and no source tree. It
//! holds no secret it wasn't given literally — `{ env = "VAR" }` references are
//! preserved and resolved where the artifact runs.
//!
//! The artifact is **generated-only, but reviewable**: like `Cargo.lock`, flusso
//! owns and rewrites it, and hand edits are not a supported input — yet it is
//! plain TOML, so a committed lock diffs meaningfully. Output is byte-stable:
//! the same inputs always serialize to the same bytes, and nothing in the
//! envelope changes just because the flusso binary was upgraded.

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::Config;
use crate::loader::{self, LoadError};

/// The artifact format version, checked on load.
///
/// Compatibility policy for the current major: additive changes to the
/// serialized shape use `#[serde(default)]` (plus `skip_serializing_if` on the
/// write side) and need **no** bump — an older lock keeps loading on a newer
/// binary. A bump marks an incompatible reshape and obliges the bumping release
/// to keep a *reader* for every prior version of the major, so the bump is a
/// migration trigger, never a rejection. Version 1 was the pre-freeze
/// MessagePack format, sanctioned as the last break; it is rejected with a
/// regenerate hint (see [`CompileError::LegacyFormat`]).
pub const FORMAT_VERSION: u8 = 2;

/// The comment header written at the top of every artifact. Static text — part
/// of the byte-stable output, never derived from the producing binary.
const HEADER: &str = "\
# This file is generated by flusso from `flusso.toml` and the schemas it references.\n\
# It is not intended for manual editing.\n";

/// A compiled configuration: the validated [`Config`] plus the format version
/// needed to read it safely.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Compiled {
    /// Artifact format version, checked on load against [`FORMAT_VERSION`].
    pub format_version: u8,
    /// The fully-validated configuration.
    pub config: Config,
}

#[derive(thiserror::Error, Debug)]
pub enum CompileError {
    #[error(transparent)]
    Load(#[from] LoadError),
    #[error("failed to read compiled config `{path}`: {source}")]
    Read {
        path: std::path::PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to write compiled config `{path}`: {source}")]
    Write {
        path: std::path::PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to encode compiled config: {0}")]
    Encode(#[from] toml::ser::Error),
    #[error("failed to decode compiled config: {0}")]
    Decode(#[from] toml::de::Error),
    #[error(
        "compiled config format version {got} is not supported by this build \
         (expected {expected}); recompile with a matching `flusso`"
    )]
    VersionMismatch { got: u8, expected: u8 },
    #[error(
        "this is not a text lock — it was likely written by an older flusso \
         (the pre-freeze binary format); re-run `flusso build` or `flusso run` \
         with the config to regenerate it"
    )]
    LegacyFormat,
}

/// Compile a `flusso.toml` (and the schemas it references) into a [`Compiled`]
/// envelope. Needs neither a database nor any secret to be set — schemas are
/// self-describing and secrets are deferred.
pub fn compile(config_path: impl AsRef<Path>) -> Result<Compiled, CompileError> {
    let config = loader::load(config_path)?;
    Ok(Compiled {
        format_version: FORMAT_VERSION,
        config,
    })
}

/// Serialize a [`Compiled`] envelope to its TOML bytes. Deterministic: the same
/// envelope always yields the same bytes.
pub fn to_bytes(compiled: &Compiled) -> Result<Vec<u8>, CompileError> {
    let body = toml::to_string(compiled)?;
    Ok(format!("{HEADER}\n{body}").into_bytes())
}

/// Write a [`Compiled`] envelope to `path` as TOML.
pub fn write(compiled: &Compiled, path: impl AsRef<Path>) -> Result<(), CompileError> {
    let path = path.as_ref();
    let bytes = to_bytes(compiled)?;
    write_bytes(&bytes, path)
}

/// Write a [`Compiled`] envelope to `path` unless the file already holds
/// exactly those bytes. Returns whether it wrote — so a no-change rebuild
/// leaves the file (and its mtime) untouched instead of churning a committed
/// lock.
pub fn write_if_changed(compiled: &Compiled, path: impl AsRef<Path>) -> Result<bool, CompileError> {
    let path = path.as_ref();
    let bytes = to_bytes(compiled)?;
    if std::fs::read(path).is_ok_and(|existing| existing == bytes) {
        return Ok(false);
    }
    write_bytes(&bytes, path)?;
    Ok(true)
}

fn write_bytes(bytes: &[u8], path: &Path) -> Result<(), CompileError> {
    std::fs::write(path, bytes).map_err(|source| CompileError::Write {
        path: path.to_path_buf(),
        source,
    })
}

/// Decode a [`Compiled`] envelope from its TOML bytes, checking the format
/// version. A non-UTF-8 input is diagnosed as the pre-freeze binary format
/// with a regenerate hint.
pub fn from_bytes(bytes: &[u8]) -> Result<Config, CompileError> {
    let text = std::str::from_utf8(bytes).map_err(|_| CompileError::LegacyFormat)?;
    let compiled: Compiled = toml::from_str(text)?;
    if compiled.format_version != FORMAT_VERSION {
        return Err(CompileError::VersionMismatch {
            got: compiled.format_version,
            expected: FORMAT_VERSION,
        });
    }
    Ok(compiled.config)
}

/// Read a compiled artifact from `path` and return its [`Config`].
pub fn load_compiled(path: impl AsRef<Path>) -> Result<Config, CompileError> {
    let path = path.as_ref();
    let bytes = std::fs::read(path).map_err(|source| CompileError::Read {
        path: path.to_path_buf(),
        source,
    })?;
    from_bytes(&bytes)
}
