//! The state machine that turns a `pgwire-replication` event stream into a
//! stream of positioned, thin [`ChangeEvent`]s.
//!
//! Row changes are buffered per transaction and only emitted once the `Commit`
//! arrives, tagged with the commit LSN. That gives every change a clean,
//! commit-aligned position to acknowledge against, and matches logical
//! decoding's "whole transactions only" model. Because events are thin (a table
//! name, primary key, and at most a pre-image), buffering even a large
//! transaction is cheap.
//!
//! Each `Relation` message is followed by a catalog lookup of the table's
//! primary key, before the next replication event is read: a change is keyed by
//! its primary key, not by the replica-identity columns pgoutput flags (all of
//! them, under `REPLICA IDENTITY FULL`). See [`pgoutput`].

use std::collections::{HashMap, HashSet, VecDeque};
use std::sync::Arc;

use futures::stream::{self, BoxStream};
use kernel::ColumnName;
use kernel::Position;
use pgwire_replication::{Lsn, ReplicationClient, ReplicationEvent};
use source::cdc::{ChangeEvent, LiveChange};
use source::{PreImageColumns, QualifiedTable, Result, SourceError};
use sqlx::PgPool;

use super::ack::Positions;
use super::pgoutput::{self, Decoded, Relation};
use super::replica_identity;

/// Everything the unfold loop carries between polls.
struct State {
    client: ReplicationClient,
    /// Catalog connection for the per-relation primary-key lookup.
    catalog: PgPool,
    decode: DecodeState,
}

/// The buffering/progress state [`handle`] folds replication events into —
/// everything except the connection, so tests can drive it with synthetic
/// events.
struct DecodeState {
    /// Relation metadata by OID, accumulated from `Relation` messages.
    relations: HashMap<u32, Relation>,
    /// Relations whose primary key has not been looked up yet.
    unkeyed: Vec<u32>,
    /// Per table, the columns resolution needs from a pre-image.
    pre_image_links: PreImageColumns,
    /// Per relation, the needed pre-image columns its replica identity does not
    /// carry — set when its `Relation` arrives.
    untraceable: HashMap<u32, Vec<ColumnName>>,
    /// Relations already warned about as untraceable.
    warned: HashSet<u32>,
    /// Row changes of the currently open transaction, awaiting its `Commit`.
    open_txn: Vec<ChangeEvent>,
    /// Changes ready to emit, each with the commit LSN to acknowledge at.
    pending: VecDeque<(ChangeEvent, u64)>,
    ack: Arc<Positions>,
    /// Set once the underlying stream is finished; drains `pending`, then ends.
    done: bool,
}

/// Build the live-changes stream from a connected client.
///
/// This carries only live changes; a backfill, when a sink needs one, is a
/// separate snapshot stream (see [`super::backfill`]). Each emitted change
/// registers its commit LSN against `ack` and is tagged with the resulting
/// [`Position`]; the capture's `confirm` reports how far the engine has durably
/// confirmed, so the slot's `confirmed_flush_lsn` advances only that far. While
/// the watched tables are idle, keepalive WAL ends and filtered-out commits
/// feed the same bookkeeping ([`Positions::register_confirmed`]), so the slot
/// keeps advancing and the server can recycle WAL generated by unrelated
/// traffic.
pub(crate) fn build(
    client: ReplicationClient,
    catalog: PgPool,
    pre_image_links: PreImageColumns,
    ack: Arc<Positions>,
) -> BoxStream<'static, Result<LiveChange>> {
    let state = State {
        client,
        catalog,
        decode: DecodeState {
            relations: HashMap::new(),
            unkeyed: Vec::new(),
            pre_image_links,
            untraceable: HashMap::new(),
            warned: HashSet::new(),
            open_txn: Vec::new(),
            pending: VecDeque::new(),
            ack,
            done: false,
        },
    };

    Box::pin(stream::unfold(state, |mut state| async move {
        loop {
            // Report how far the engine has durably confirmed so the slot can
            // advance and the server can recycle WAL.
            state
                .client
                .update_applied_lsn(Lsn::from_u64(state.decode.ack.confirmed_lsn()));

            if let Some((event, lsn)) = state.decode.pending.pop_front() {
                let seq = state.decode.ack.register(lsn);
                return Some((Ok((Position(seq), event)), state));
            }

            if state.decode.done {
                return None;
            }

            match state.client.recv().await {
                Ok(Some(event)) => {
                    let handled = match handle(&mut state.decode, event) {
                        Ok(()) => key_relations(&state.catalog, &mut state.decode).await,
                        Err(e) => Err(e),
                    };
                    if let Err(e) = handled {
                        state.decode.done = true;
                        return Some((Err(e), state));
                    }
                }
                Ok(None) => state.decode.done = true,
                Err(e) => {
                    state.decode.done = true;
                    return Some((Err(map_pgwire(e)), state));
                }
            }
        }
    }))
}

/// Look up the catalog primary key of every relation announced since the last
/// event, then which parent links its identity can't deliver (that depends on
/// the key). A table without one keeps an empty key and is keyed by its
/// replica identity instead.
async fn key_relations(
    catalog: &PgPool,
    state: &mut DecodeState,
) -> std::result::Result<(), SourceError> {
    for oid in std::mem::take(&mut state.unkeyed) {
        let Some(relation) = state.relations.get_mut(&oid) else {
            continue;
        };
        let qualified = format!(
            "{}.{}",
            super::quote_ident(relation.namespace.as_ref()),
            super::quote_ident(relation.table.as_ref())
        );
        relation.primary_key = crate::document::primary_key_column_names(catalog, qualified)
            .await?
            .into_iter()
            .map(|name| {
                ColumnName::try_new(name.clone()).map_err(|e| {
                    SourceError::Decode(format!("invalid primary key column {name:?}: {e}"))
                })
            })
            .collect::<std::result::Result<_, _>>()?;
        record_untraceable(state, oid);
    }
    Ok(())
}

/// Fold one replication event into the state, possibly queueing changes.
fn handle(
    state: &mut DecodeState,
    event: ReplicationEvent,
) -> std::result::Result<(), SourceError> {
    match event {
        // The worker replies to keepalives; here the reported WAL end feeds the
        // watermark so the slot advances while the watched tables are idle.
        // Buffered or queued changes are not registered yet, so confirming past
        // them would lose their positions — hence the emptiness guard. Changes
        // already emitted need no guard: their sequences precede this one and
        // hold the watermark back until the engine confirms them.
        ReplicationEvent::KeepAlive { wal_end, .. } => {
            if state.open_txn.is_empty() && state.pending.is_empty() {
                state.ack.register_confirmed(wal_end.as_u64());
            }
        }

        // Logical messages are not changes.
        ReplicationEvent::Message { .. } => {}

        ReplicationEvent::Begin { .. } => state.open_txn.clear(),

        ReplicationEvent::Commit { end_lsn, .. } => {
            let lsn = end_lsn.as_u64();
            if state.open_txn.is_empty() {
                // A transaction the publication filtered out entirely (PG < 16
                // still streams its Begin/Commit) — account its position so it
                // doesn't pin WAL retention. Same guard rationale as keepalive.
                if state.pending.is_empty() {
                    state.ack.register_confirmed(lsn);
                }
            } else {
                for change in state.open_txn.drain(..) {
                    state.pending.push_back((change, lsn));
                }
            }
        }

        // Stop requested / stop_at_lsn reached: drain what we have, then end.
        ReplicationEvent::StoppedAt { .. } => state.done = true,

        ReplicationEvent::XLogData { data, .. } => handle_xlog(state, data.as_ref())?,
    }
    Ok(())
}

fn handle_xlog(state: &mut DecodeState, data: &[u8]) -> std::result::Result<(), SourceError> {
    match pgoutput::decode(data)? {
        Decoded::Relation(relation) => {
            state.unkeyed.push(relation.oid);
            state.relations.insert(relation.oid, relation);
        }
        Decoded::Insert { rel, new } => {
            let relation = lookup_relation(state, rel)?;
            let table = relation.table.clone();
            let key = pgoutput::row_key(relation, &new)?;
            state.open_txn.push(ChangeEvent::Upsert {
                table,
                key,
                before: None,
            });
        }
        Decoded::Update { rel, old, new } => {
            let relation = lookup_relation(state, rel)?;
            let table = relation.table.clone();
            let new_key = pgoutput::row_key(relation, &new)?;
            // A primary-key change is a delete of the old document plus an
            // upsert of the new one.
            let old_key = match &old {
                Some(old) => Some(pgoutput::row_key(relation, old)?),
                None => None,
            };
            let before = old
                .as_ref()
                .and_then(|old| pgoutput::pre_image(relation, old));
            if let Some(old_key) = old_key
                && old_key.0 != new_key.0
            {
                state.open_txn.push(ChangeEvent::Delete {
                    table: table.clone(),
                    key: old_key,
                    before: before.clone(),
                });
            }
            state.open_txn.push(ChangeEvent::Upsert {
                table,
                key: new_key,
                before,
            });
            warn_untraceable(state, rel);
        }
        Decoded::Delete { rel, old } => {
            let relation = lookup_relation(state, rel)?;
            let table = relation.table.clone();
            let key = pgoutput::row_key(relation, &old)?;
            let before = pgoutput::pre_image(relation, &old);
            state
                .open_txn
                .push(ChangeEvent::Delete { table, key, before });
            warn_untraceable(state, rel);
        }
        Decoded::Truncate { rels } => {
            for oid in rels {
                let table = state
                    .relations
                    .get(&oid)
                    .map(|r| r.table.to_string())
                    .unwrap_or_else(|| format!("oid {oid}"));
                // No Truncate variant in the core vocabulary yet; surface it
                // loudly rather than silently leaving the index stale.
                tracing::warn!(%table, "TRUNCATE received but not propagated; index may be stale");
            }
        }
        Decoded::Other => {}
    }
    Ok(())
}

/// Record which pre-image columns relation `oid` needs but can't deliver —
/// what an update or delete on it can't trace to the old parent.
fn record_untraceable(state: &mut DecodeState, oid: u32) {
    let Some(relation) = state.relations.get(&oid) else {
        return;
    };
    let table = QualifiedTable::new(relation.namespace.clone(), relation.table.clone());
    let required = state
        .pre_image_links
        .get(&table)
        .map(Vec::as_slice)
        .unwrap_or_default();
    let carries = |name: &str| {
        relation
            .columns
            .iter()
            .any(|column| column.is_key && column.name.as_ref() == name)
    };
    let uncarried = replica_identity::uncarried(carries, &relation.primary_key, required);
    if uncarried.is_empty() {
        state.untraceable.remove(&oid);
    } else {
        state.untraceable.insert(oid, uncarried);
    }
}

/// Warn, once per relation, about an update or delete on a table whose replica
/// identity doesn't carry its parent link — so a delete or re-parent leaves
/// the old parent's document stale.
fn warn_untraceable(state: &mut DecodeState, oid: u32) {
    let (Some(uncarried), Some(relation)) =
        (state.untraceable.get(&oid), state.relations.get(&oid))
    else {
        return;
    };
    if !state.warned.insert(oid) {
        return;
    }
    let table = QualifiedTable::new(relation.namespace.clone(), relation.table.clone());
    replica_identity::warn_untraceable(
        &table,
        uncarried,
        "an update or delete arrived without it",
        &replica_identity::alter_sql(relation.namespace.as_ref(), relation.table.as_ref()),
    );
}

/// Look up a relation by OID. A missing one means a DML message arrived before
/// its `Relation` — a protocol violation we can't decode past.
fn lookup_relation(state: &DecodeState, oid: u32) -> std::result::Result<&Relation, SourceError> {
    state.relations.get(&oid).ok_or_else(|| {
        SourceError::Decode(format!("pgoutput: change for unknown relation oid {oid}"))
    })
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests;

/// Map a replication error onto the source's transient/fatal split.
fn map_pgwire(error: pgwire_replication::PgWireError) -> SourceError {
    use pgwire_replication::PgWireError;
    if error.is_transient() {
        return SourceError::Connection(error.to_string());
    }
    match error {
        PgWireError::Server(_) | PgWireError::Auth(_) | PgWireError::Tls(_) => {
            SourceError::Setup(error.to_string())
        }
        PgWireError::Protocol(_) => SourceError::Decode(error.to_string()),
        other => SourceError::Connection(other.to_string()),
    }
}
